# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Oscar Portfolio
email: oscarian528@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Ian Oscar is a Software Engineer specializing in backend development, RESTful APIs, Python, Django, Flask, and DevOps. 
  Explore his portfolio, experience, and certifications in software engineering and AI integration.
twitter_username: username
github_username: username
minimal_mistakes_skin: neon
search: false

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 0 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages
  - _projects
  - _labs

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-remote-feed

# for medium
remote_feed:
  url: "https://medium.com/feed/@oscarian528"  # Replace with your Medium username
  limit: 5

author:
  name   : "Ian Oscar"
  # avatar : "/assets/images/bio-photo.jpg"
  avatar : "/assets/images/profile-photo.jpg"
  # bio    : "Software Engineer. Passionate about solving complex problems and building efficient solutions."
  bio: |
    Software Engineer.
    Building resilient backend systems with clean code, curiosity, and purpose.
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/theeduke"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/oscar-ian/"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:oscarian528@gmail.com"
    # - label: "Website"
      #   icon: "fas fa-fw fa-link"
      #   url: "https://"
    # - label: "Twitter"
      #   icon: "fab fa-fw fa-twitter-square"
      #   url: "https://twitter.com/"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/theeduke"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/oscar-ian/"
    # - label: "Twitter"
      #   icon: "fab fa-fw fa-twitter-square"
      #   url: "https://twitter.com/"

defaults:
  # # _posts
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "splash"
      author_profile: true
  # - scope:
  #     path: ""
  #     type: posts
  #   values:
  #     layout: single
  #     author_profile: true
  #     read_time: true
  #     comments: true
  #     share: true
  #     related: true
  # _pages
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "single"
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  # - scope:
        # path: "_pages"
        # type: pages
  #   values:
  #     layout: single
  #     author_profile: true
collections:
  projects:
    output: true
    permalink: /:collection/:path/
  labs:
    output: true
    permalink: /:collection/:path/

# category_archive:
#   type: liquid
#   path: /categories/
# tag_archive:
#   type: liquid
#   path: /tags/
